var a;
a = 4.20;
console.log(a);
var b = 0;
b += 1;
b ++;
console.log(b);
var c = 3;
var d = c;
d = c + 4;
console.log(d);
var z1 = 80;
var z2 = z1 * 3;
var z3 = z1 + z2;
var z4;
z4 = z3 * z2;
z2 = z1 / 8;
console.log("la valeur de z1 est:" + z1);
console.log("la valoeur de z3 est:" + z3);
console.log("la valeur de z4 est:" + z4);
var h = "5";
console.log(h + 1);
h = Number("5");
console.log(h + 2);